### ISSUE TITLE
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by YH188** [bharat-b7/RVH_Mesh_Registration#23]
How can this problem be solved?

Traceback (most recent call last):
  File "smpl_registration/fit_SMPLH.py", line 17, in <module>
    from pytorch3d.loss import point_mesh_face_distance
  File "/home/yin/miniconda3/envs/rvh-mesh-env/lib/python3.7/site-packages/pytorch3d/loss/__init__.py", line 4, in <module>
    from .chamfer import chamfer_distance
  File "/home/yin/miniconda3/envs/rvh-mesh-env/lib/python3.7/site-packages/pytorch3d/loss/chamfer.py", line 7, in <module>
    from pytorch3d.ops.knn import knn_gather, knn_points
  File "/home/yin/miniconda3/envs/rvh-mesh-env/lib/python3.7/site-packages/pytorch3d/ops/__init__.py", line 5, in <module>
    from .graph_conv import GraphConv
  File "/home/yin/miniconda3/envs/rvh-mesh-env/lib/python3.7/site-packages/pytorch3d/ops/graph_conv.py", line 8, in <module>
    from pytorch3d import _C
ImportError: libc10_cuda.so: cannot open shared object file: No such file or directory

**Comment by Joon-Jung** [comment]
I solved that error by installing pytorch with CUDA support through command below on anaconda:
`conda install pytorch==1.7.1 torchvision==0.8.2 torchaudio==0.7.2 cudatoolkit=10.2 -c pytorch`
